### ISSUE TITLE
enhancement: Retrofit with jake wharton's coroutines adapter

### ISSUE THREAD

**Issue by neiljaywarner** [android/sunflower#191]
very simple 
try/catch http exception/catch regular exception would be super nice
it is so nice
https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter

**Comment by XinyueZ** [comment]
This demo loads local data, however, I am also looking forward a remote data feature in the future.

**Comment by neiljaywarner** [comment]
i see your point... But Jake is there at google, Retrofit is in jetpack guide, and coroutines are leaving experimental in 1.3, and there's several  articles about the merit of moving from Rx to Coroutines, even (i think) from Chris Banes.. I think..

**Comment by XinyueZ** [comment]
@neiljaywarner Yeah, RX should be replaced by coroutine in the future Android development which is a point of my view. Actually, there's a corner of the current codebase which can be used with coroutine.
 https://github.com/googlesamples/android-sunflower/blob/master/app/src/main/java/com/google/samples/apps/sunflower/utilities/AppExecutors.kt#L27

**Comment by tiembo** [comment]
@neiljaywarner yes, there are plans to incorporate retrofit and coroutines into Sunflower.  Keep an eye on #208

**Comment by tiembo** [comment]
Added in #625
