### ISSUE TITLE
Missing resource flow_horizontalSeparator

### ISSUE THREAD

**Issue by kamilj** [android/sunflower#499]
Build Output:
AAPT: error: resource attr/flow_horizontalSeparator (aka com.google.samples.apps.sunflower:attr/flow_horizontalSeparator) not found.

> 
        Android Studio 3.6 Canary 7
        // Sdk and tools
        compileSdkVersion = 28
        minSdkVersion = 19
        targetSdkVersion = 28

        // App dependencies
        appCompatVersion = '1.1.0-beta01'
        constraintLayoutVersion = '2.0.0-beta1'
        coreTestingVersion = '2.0.0'
        coroutinesVersion = "1.3.0-M2"
        espressoVersion = '3.1.1'
        fragmentVersion = '1.1.0-alpha09'
        glideVersion = '4.9.0'
        gradleVersion = '3.6.0-alpha07'
        gsonVersion = '2.8.2'
        junitVersion = '4.12'
        kotlinVersion = '1.3.41'
        ktlintVersion = '0.30.0'
        ktxVersion = '1.0.2'
        lifecycleVersion = '2.2.0-alpha01'
        materialVersion = '1.0.0'
        navigationVersion = '2.0.0'
        recyclerViewVersion = '1.1.0-alpha05'
        roomVersion = '2.1.0'
        runnerVersion = '1.0.1'
        truthVersion = '0.42'
        testExtJunit = '1.1.0'
        uiAutomatorVersion = '2.2.0'
        workVersion = '2.1.0'

**Comment by VMadalin** [comment]
@kamilj Thank you for the reported issue. After a little research I found this https://github.com/android/views-widgets-samples/issues/37 

> This is the relevant issue in the Google tracker https://issuetracker.google.com/issues/136103084
>
>  The recommendation for now is to either:
> - Downgrade Android Studio (3.6 alpha 2 works fine for me, alpha 3 creates this issue with ConstraintLayout 2 or any other library that uses attrs the old way)
> - Add the attrs that are missing to your project. When another version of ConstraintLayout library is released with the attrs included you'll have to remove them from your project.

**Comment by calren** [comment]
I believe this issue should now be resolved if you're using Android Studio Arctic Fox
