### ISSUE TITLE
Some plant titles do not appear on title bar due to limited scroll

### ISSUE THREAD

**Issue by tiembo** [android/sunflower#502]
Screenshot from Pixel 3 XL with page scrolled up all the way.

![device-2019-08-28-123145](https://user-images.githubusercontent.com/97128/63886716-ff2a9d80-c98f-11e9-9fcb-2ed1ff5e95cb.png)

**Comment by zhaonian** [comment]
Could not reproduce on Pixel 3XL :/

**Comment by sowmyamangati** [comment]
Hi ,
Tested on Pixel 3XL Emulator ,When Scrolled Up Title is properly displaying ,attached screen shot for reference.

![Pixel_3XL_Title](https://user-images.githubusercontent.com/54341672/67016426-cbc9dc80-f0bd-11e9-9c14-89b5b36e9d4f.png)

**Comment by chandmohd** [comment]
Hi,

**Comment by chandmohd** [comment]
Hi,

**Comment by chandmohd** [comment]
HI,
There was issue with minHeight in plant desc textView.
I have tested with  Pixel 3XL/4XL Emulator working as expected.
![sunflower](https://user-images.githubusercontent.com/32665518/125183956-dcc66400-e237-11eb-8817-afb86f0faabc.png)
#729
