### ISSUE TITLE
Crash on scrolling plant details

### ISSUE THREAD

**Issue by dansef** [android/sunflower#510]
2019-09-08 07:55:14.203 2723-2800/? E/OpenGLRenderer: resultIndex is -1, the polygon must be invalid!
2019-09-08 07:55:14.204 2723-2800/? A/OpenGLRenderer: Error: Spot pair overflow!!! used 38, total 22
2019-09-08 07:55:14.206 2723-2800/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 2800 (hwuiTask1), pid 2723 (.apps.sunflower)

**Comment by VMadalin** [comment]
I reproduce this same strange issue, on my device: 
- Device type: VFD 600
- OS version: Android 6.0.1

```
09-09 16:24:12.513 24958-24958/com.google.samples.apps.sunflower V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@52b0c2c
09-09 16:24:12.513 24958-24958/com.google.samples.apps.sunflower V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@711c6f5
09-09 16:24:12.574 24958-24958/com.google.samples.apps.sunflower W/FragmentManager: moveToState: Fragment state for HomeViewPagerFragment{8386630 (a0641f56-aa6a-4b4a-906b-7f272c8a1c49) id=0x7f0800e3} not updated inline; expected state 1 found 2
09-09 16:24:14.373 24958-24994/com.google.samples.apps.sunflower A/libc: Fatal signal 7 (SIGBUS), code 1, fault addr 0x4eb in tid 24994 (hwuiTask1)
```

**Comment by VMadalin** [comment]
Finally and after a little research I found where is produced the crash. Basically this crash is only reproducible on `detail` of `plant list` section, the only difference with the `detail` of the `my garden` section is the `FloatingActionButton`.  Apparently for some strange reason the `ShapeAppearance.Sunflower.FAB` cause this problem when we set it on `shapeAppearance` as a non symmetric style. This issue don't happens on new android versions (I cannot reproduce the issue with new android versions)

Example working styles: 

```
<style name="ShapeAppearance.Sunflower.FAB" parent="ShapeAppearance.MaterialComponents">
        <item name="cornerFamily">rounded</item>
 </style>

<style name="ShapeAppearance.Sunflower.FAB" parent="ShapeAppearance.MaterialComponents">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSizeTopLeft">0dp</item>
        <item name="cornerSizeTopRight">0dp</item>
        <item name="cornerSizeBottomRight">0dp</item>
        <item name="cornerSizeBottomLeft">0dp</item>
 </style>

...
```

**Comment by ashraf-patel** [comment]
https://github.com/android/sunflower/commit/5b9f9cda8f4568ad0977ad6eb4dc8946ae657657

@tiembo PR should fix this as well.

**Comment by tiembo** [comment]
Thanks for the message @ashraf-patel.  Indeed, #537 should fix this; please comment if this is still happening in master.
