### ISSUE TITLE
Documentation discontiniousy

### ISSUE THREAD

**Issue by baalimago** [android/sunflower#513]
Hello,

If you take a look at the https://developer.android.com/guide/navigation/navigation-principles this project is referenced, but the project looks completely different now than it did when that article was made (not sure when it was written, or by who, it wasn't listed).

I'm lacking another place to report this, just thought you guys should know.

Thanks for an otherwise great product! It'll help alot.

**Comment by tiembo** [comment]
Thanks for reporting this!

For issues related to documentation on developer.android.com, please create a new issue in the [Google issue tracker](https://issuetracker.google.com).  The specific component for DAC is [here](https://issuetracker.google.com/issues/new?component=192697)
