### ISSUE TITLE
Crash while adding the plant

### ISSUE THREAD

**Issue by ashraf-patel** [android/sunflower#519]
App crashes when I click on `add_plant` Button(FAB)
```
2019-10-03 23:17:35.509 6603-6631/com.google.samples.apps.sunflower E/OpenGLRenderer: resultIndex is -1, the polygon must be invalid!
2019-10-03 23:17:35.510 6603-6631/com.google.samples.apps.sunflower A/OpenGLRenderer: Error: Spot pair overflow!!! used 38, total 22
--------- beginning of crash
2019-10-03 23:17:35.510 6603-6631/com.google.samples.apps.sunflower A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 6631 (hwuiTask1)
```

**Comment by ashraf-patel** [comment]
Somehow making this change to the below file fixes it. But the shape will be different of course.
```    
<style name="ShapeAppearance.Sunflower.FAB" parent="ShapeAppearance.MaterialComponents">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSizeTopLeft">0dp</item>
        <item name="cornerSizeTopRight">0dp</item>
        <item name="cornerSizeBottomRight">0dp</item>
        <item name="cornerSizeBottomLeft">0dp</item>
</style>
```

**Comment by tiembo** [comment]
Thanks for the report.  What device and version are you running the app with?

**Comment by ashraf-patel** [comment]
Device: Pixel 2 XL Emulator
OS: 8.0

**Comment by smdufb** [comment]
Can confirm. Happens for me too when adding **the first** item.

**Comment by sowmyamangati** [comment]
Hi, I have tested on Pixel 2XL Emulator ,OS:8.0, the app is not crashing while clicking on Add_plant FAB for the first time , attached video  for 
[Add_plant.webm.zip](https://github.com/android/sunflower/files/3739969/Add_plant.webm.zip)

 reference

**Comment by ashraf-patel** [comment]
@sowmyamangati 
Material component FAB is causing the crash when you scroll. 
You can follow https://github.com/material-components/material-components-android/issues/661
and you can check https://github.com/ashraf-patel/MaterialComponentsDemo out if you want to see it crash.

**Comment by sowmyamangati** [comment]
Thanks @ashraf-patel, previously I tested by repeatedly adding plants . After your comments  I was able to replicate the crash by scrolling on the plant details screen .

**Comment by nic0lette** [comment]
Digging into this more, it's easier to reproduce the crash by scrolling up and down very quickly so the FAB appears and disappears.

This appears to be a platform specific bug (probably as you suspected), so it doesn't seem to happen on Android 10 (or at least I couldn't get it to happen on my actual device.)

**Comment by ashraf-patel** [comment]
@nic0lette 
Material component FAB is causing the crash when you scroll.
You can follow material-components/material-components-android#661
and you can check https://github.com/ashraf-patel/MaterialComponentsDemo out if you want to see it crash.
