### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by IgorGanapolsky** [android/sunflower#532]
See the following compilation error in A.S. 3.5.1:
<img width="1676" alt="Screen Shot 2019-10-19 at 3 37 37 PM" src="https://user-images.githubusercontent.com/201209/67150536-99b7a680-f286-11e9-884b-398ca063cccf.png">

**Comment by nic0lette** [comment]
I just cloned the project clean and opened it in 3.5.1, and even checking out this class specifically I'm not seeing the error?

Could you try again (with a clean version of the project and potentially clearing/invalidating caches)?

Thank you!

**Comment by IgorGanapolsky** [comment]
Yes, apparently upgrading gradle dependencies and material design deps caused the issue.  I reset my git branch to head and it builds now.
