### ISSUE TITLE
crash by android.content.res.Resources$NotFoundException 

### ISSUE THREAD

**Issue by ada24y** [android/sunflower#544]
it appearance in api 19 .
Unable to start activity ComponentInfo{com.google.samples.apps.sunflower/com.google.samples.apps.sunflower.GardenActivity}: android.content.res.Resources$NotFoundException: File res/drawable/garden_tab_selector.xml from drawable ... 

Also 
 E/dalvikvm: Could not find class 'android.view.WindowInsets', referenced from method androidx.core.view.ViewCompat.onApplyWindowInsets
E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.google.android.material.tabs.TabLayout$TabView.updateBackgroundDrawable
/dalvikvm: Could not find class 'android.view.accessibility.AccessibilityNodeInfo$AccessibilityAction', referenced from method androidx.core.view.accessibility.AccessibilityNodeInfoCompat$AccessibilityActionCompat.getId
....

**Comment by tiembo** [comment]
Sunflower is updating to API 21 (#545 ), so this issue should be solved by that.  Please comment if you are still running into this issue once the API 21 change is merged.  Thanks!
