### ISSUE TITLE
Lack  databinding package

### ISSUE THREAD

**Issue by seuer** [android/sunflower#558]
When I read  PlantDetailFragment code, I identify a lack of  the package of databinding.

**Comment by tiembo** [comment]
Can you add more details to your issue?

**Comment by seuer** [comment]
This is my screenshot from sunflower project
![image](https://user-images.githubusercontent.com/8774888/69314914-4adba300-0c70-11ea-8690-9ff137a07129.png)

**Comment by seuer** [comment]
@tiembo hello, Could you help me  ?

**Comment by nic0lette** [comment]
Hi @seuer 

The class `com.google.samples.apps.sunflower.databinding.FragmentPlantDetailBinding` is generated by Gradle (well, a plugin), and so when I import and open the project, there isn't an error.

So, if you could add more details to the issue, explaining what OS you're using, the version of Android Studio, etc... then we may be able to help you better.

The only suggestion I have at the moment is to be sure you're using Android Studio version 3.5.2 (the latest stable at the moment), and that you try using "**Import Project**" with a clean copy of the repo.

You might also try to use **File > Invalidate Caches / Restart** in Android Studio and see if that fixes the issu.

**Comment by seuer** [comment]
@nic0lette  ok, you have my  heartfelt  thanks.
