### ISSUE TITLE
lifecycleOwner is not recognized.

### ISSUE THREAD

**Issue by seuer** [android/sunflower#564]
![image](https://user-images.githubusercontent.com/8774888/70981218-b7bb4f00-20ef-11ea-8664-dce0002eb9ea.png)
When  I use Android Studio  3.5.2 to import sunflower project, I  wonder   this lifecycleOwner is not recognized in PlantDetailFragment.kt. I  have no idea  to fix the problem.  Could you  help me? @nic0lette @tiembo , thanks a lot !

**Comment by nic0lette** [comment]
Hi @seuer 

I tried using a fresh copy of Sunflower that's synced with master from GitHub but I couldn't reproduce the problem.

My suggestion is to try to use **File > Invalidate Caches / Restart** in Android Studio and see if that fixes the issue. Then, if it does not, try to make a fresh clone of the project and use "**Import Project**".

**Comment by seuer** [comment]
@nic0lette   thank you for your support, I have fixed  my problem and  I can run the project normally on my device.

**Comment by nic0lette** [comment]
Great to hear! =D
