### ISSUE TITLE
Share wiki page

### ISSUE THREAD

**Issue by jsnider** [android/sunflower#567]
I wanted to share the info about the avacado but it just shared a string which I thought was pretty lame. Would it be possible to add the wikipedia page url along with the name.

I know you're not looking for new features, but I think it would be a nice addition.

**Comment by tiembo** [comment]
Added some comments to the PR.

**Comment by tiembo** [comment]
Closing due to closing associated PR #586.  Please comment if you want to resume discussion.  Thanks!
