### ISSUE TITLE
Why can't ImageView use the property imagefromurl in my project

### ISSUE THREAD

**Issue by qinmr** [android/sunflower#571]
Why can't ImageView use the property imagefromurl in my project? I use the same compiler as demo

**Comment by qinmr** [comment]
This problem occurs in list item garden planning.xml

**Comment by qinmr** [comment]
This problem occurs in list_item_garden_planting.xml

**Comment by tiembo** [comment]
Could you provide an example of how it's used in your project?

**Comment by qinmr** [comment]
`<ImageView
                android:id="@+id/imageView"
                android:layout_width="0dp"
                android:layout_height="@dimen/plant_item_image_height"
                android:contentDescription="@string/a11y_plant_item_image"
                android:scaleType="centerCrop"
                app:imageFromUrl="@{model.imageUrl}"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />`like it，This property will not be wrong in this project, but it cannot be compiled in my project. Why?imagefromurl

> 您能否提供一个示例说明如何在项目中使用它？

**Comment by qinmr** [comment]
> Could you provide an example of how it's used in your project?

I should have found my mistake. I didn't use it
`@BindingAdapter`

**Comment by qinmr** [comment]
oh，thanks

**Comment by linversion** [comment]
> oh，thanks

最后是什么解释？这个属性哪来的？
What is the final explanation? Where does this attribute come from?
