### ISSUE TITLE
Filter condition (GrowZone) in PlantListViewModel should be persisted across process death

### ISSUE THREAD

**Issue by Zhuinden** [android/sunflower#572]
https://github.com/android/sunflower/blob/2da1ffa71f687e5eeeee0f9b0513782caed8d3cc/app/src/main/java/com/google/samples/apps/sunflower/viewmodels/PlantListViewModel.kt#L32

With the release of ViewModel-SavedState 1.0.0, the filter condition should be preserved across process death via `SavedStateHandle.getLiveData("growZone")`.

**Comment by tiembo** [comment]
Thanks for the suggestion!  We'll look into adding it.
