### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by JoeCodeswell** [android/sunflower#586]
Hi folks. I'm kind of a Newbie to Android. I am following [Android Kotlin Fundamentals 01.4: Learn to help yourself](https://codelabs.developers.google.com/codelabs/kotlin-android-training-available-resources/#3). I tried to "In Android Studio, open the android-sunflower-master project." 

It wasn't totally clear to me exactly how to go about that, but here's what I did using Android Studio 3.6.1..
1. open Android Studio Welcome
2. click "open file or project"
3. nav to `C:\1d\AndroidApps\AndroidKotlinFundamentals\4 Task Learn from sample code\sunflower-master\build.gradle`
4. click OK
RESULT:
... `gradle sync finished in 1m 9s`
5. clicked run on *Pixel 2 XL API 24* - iPhone7Plus
RESULT 
``` text
> Task :app:kaptDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 56s
19 actionable tasks: 1 executed, 18 up-to-date
```
Please let me know if there's anything more I can do to help. Thanks.
Love and peace,
Joe Dorocak aka Joe Codeswell

**Comment by nunofaria11** [comment]
I am getting the same error

**Comment by art-tykh** [comment]
Any news on this issue? I am getting the same error.

**Comment by tiembo** [comment]
Hi there - thank you for the reports.  The codelab might be out of date - here's how to can load the Sunflower example from Android Studio (tested using Studio 3.6.3):

- In the welcome screen, click on "Import an Android code sample"
- In the search box, type in "sunflower"
- Select any one of the Sunflower entries (they refer to the same sample) and click Next
- Select a location to store the sample code, and click Finish.

Closing this issue on the Sunflower project as this issue mostly pertains to the codelab instructions.  For issues with the Android Fundamentals codelab, please also file an issue [here](https://github.com/google-developer-training/android-kotlin-fundamentals-apps/issues/new?assignees=&labels=&template=android-kotlin-fundamentals.md&title=Android+Kotlin+Fundamentals+codelab%3A+).  Thank you!

**Comment by art-tykh** [comment]
@tiembo I am afraid this is not the issue with codelab instruction. I am still getting the same error. Android Studio 3.6.3, Kotlin: 1.3.41, Gradle 5.6.4

**Comment by etozturan** [comment]
Does anyone solve the problem?
