### ISSUE TITLE
Sunflower app has memory leak when jumping to PlantDetailFragment

### ISSUE THREAD

**Issue by Mckrgf** [android/sunflower#628]
Detection by LeakCanary2.4

**Comment by tiembo** [comment]
Thanks for the report.  Can you add more details about the leak?

**Comment by Mckrgf** [comment]
the leak happens when using  **PlantAdapter's navigateToPlant()** .
in method the leak canary log is here.

┬───
│ GC Root: System class
│
├─ android.view.inputmethod.InputMethodManager class
│    Leaking: NO (InputMethodManager↓ is not leaking and a class is never leaking)
│    ↓ static InputMethodManager.sInstance
├─ android.view.inputmethod.InputMethodManager instance
│    Leaking: NO (DecorView↓ is not leaking and InputMethodManager is a singleton)
│    ↓ InputMethodManager.mCurRootView
├─ com.android.internal.policy.DecorView instance
│    Leaking: NO (LinearLayout↓ is not leaking and View attached)
│    mContext instance of com.android.internal.policy.DecorContext, wrapping activity com.google.samples.apps.sunflower.GardenActivity with mDestroyed = false
│    Parent android.view.ViewRootImpl not a android.view.View
│    View#mParent is set
│    View#mAttachInfo is not null (view attached)
│    View.mWindowAttachCount = 1
│    ↓ DecorView.mContentRoot
├─ android.widget.LinearLayout instance
│    Leaking: NO (GardenActivity↓ is not leaking and View attached)
│    mContext instance of com.google.samples.apps.sunflower.GardenActivity with mDestroyed = false
│    View.parent com.android.internal.policy.DecorView attached as well
│    View#mParent is set
│    View#mAttachInfo is not null (view attached)
│    View.mWindowAttachCount = 1
│    ↓ LinearLayout.mContext
├─ com.google.samples.apps.sunflower.GardenActivity instance
│    Leaking: NO (NavHostFragment↓ is not leaking and Activity#mDestroyed is false)
│    ↓ GardenActivity.mFragments
├─ androidx.fragment.app.FragmentController instance
│    Leaking: NO (NavHostFragment↓ is not leaking)
│    ↓ FragmentController.mHost
├─ androidx.fragment.app.FragmentActivity$HostCallbacks instance
│    Leaking: NO (NavHostFragment↓ is not leaking)
│    ↓ FragmentActivity$HostCallbacks.mFragmentManager
├─ androidx.fragment.app.FragmentManagerImpl instance
│    Leaking: NO (NavHostFragment↓ is not leaking)
│    ↓ FragmentManagerImpl.mPrimaryNav
├─ androidx.navigation.fragment.NavHostFragment instance
│    Leaking: NO (HomeViewPagerFragment↓ is not leaking and Fragment#mFragmentManager is not null)
│    ↓ NavHostFragment.mChildFragmentManager
├─ androidx.fragment.app.FragmentManagerImpl instance
│    Leaking: NO (HomeViewPagerFragment↓ is not leaking)
│    ↓ FragmentManagerImpl.mActive
├─ java.util.HashMap instance
│    Leaking: NO (HomeViewPagerFragment↓ is not leaking)
│    ↓ HashMap.table
├─ java.util.HashMap$Node[] array
│    Leaking: NO (HomeViewPagerFragment↓ is not leaking)
│    ↓ HashMap$Node[].[0]
├─ java.util.HashMap$Node instance
│    Leaking: NO (HomeViewPagerFragment↓ is not leaking)
│    ↓ HashMap$Node.value
├─ com.google.samples.apps.sunflower.HomeViewPagerFragment instance
│    Leaking: NO (GardenFragment↓ is not leaking and Fragment#mFragmentManager is not null)
│    ↓ HomeViewPagerFragment.mChildFragmentManager
├─ androidx.fragment.app.FragmentManagerImpl instance
│    Leaking: NO (GardenFragment↓ is not leaking)
│    ↓ FragmentManagerImpl.mAdded
├─ java.util.ArrayList instance
│    Leaking: NO (GardenFragment↓ is not leaking)
│    ↓ ArrayList.elementData
├─ java.lang.Object[] array
│    Leaking: NO (GardenFragment↓ is not leaking)
│    ↓ Object[].[0]
├─ com.google.samples.apps.sunflower.GardenFragment instance
│    Leaking: NO (Fragment#mFragmentManager is not null)
│    Fragment.mTag=f0
│    ↓ GardenFragment.binding
│                     ~~~~~~~
├─ com.google.samples.apps.sunflower.databinding.FragmentGardenBindingImpl instance
│    Leaking: UNKNOWN
│    ↓ FragmentGardenBindingImpl.mRoot
│                                ~~~~~
╰→ android.widget.FrameLayout instance
​     Leaking: YES (ObjectWatcher was watching this because com.google.samples.apps.sunflower.GardenFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks) and View detached and has parent)
​     key = 6b6f0b9f-9351-45fe-9e17-6634360f6bd6
​     watchDurationMillis = 11137
​     retainedDurationMillis = 6135
​     mContext instance of com.google.samples.apps.sunflower.GardenActivity with mDestroyed = false
​     View#mParent is set
​     View#mAttachInfo is null (view detached)
​     View.mWindowAttachCount = 4

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: OnePlus
LeakCanary version: 2.4
App process name: com.google.samples.apps.sunflower
Analysis duration: 4449 ms

**Comment by RenHaiRenWjc** [comment]
I call FragmentStateAdapter(@NonNull FragmentManager fragmentManager,
             @NonNull Lifecycle lifecycle), this problem can be solved

**Comment by arriolac** [comment]
The app has since been migrated to Compose so this issue is obsolete. Please reopen if you see otherwise. Thanks
