### ISSUE TITLE
Why is `getPlant()` from database to ViewModel not implemented with Co-routines

### ISSUE THREAD

**Issue by eothein** [android/sunflower#648]
In practically all documentation regarding database operations and Room in Android, it is stated that all operations on the database should be asynchronous. 

If we look at the implementation of:
-  `fun getPlant(plantId: String): LiveData<Plant>`, in the `PlantDao`
- `fun getPlant(plantId: String) = plantDao.getPlant(plantId)`in the `PlantRepository`
- and `val plant = plantRepository.getPlant(plantId)` in the the `PlantDetailViewModel`

there is no co-routine implementation. What is the reason for this?  What is the difference between the create/delete operations? 

Kind regards Jens

**Comment by Kraigolas** [comment]
Hello,

To answer your question simply: in the function in question, we are working with LiveData. If you were to go in and add the keywork "suspend" to each of those functions and then call them from a co-routine, you'll see that an error is thrown. The key difference between accessing LiveData and create and delete operations is that when you create a new entity and add it to your table, there is a beginning (creation of the data) and end (insertion into the table) of that function. LiveData is constantly updating, and thus the function is effectively running in perpetuity until all references to the data is lost.

Hope this helps!

**Comment by eothein** [comment]
Ok, so if I understand it correctly - the read operation is always async of the main thread by default by room if you expect a LiveData variable? If not, you could still have a very long operation by accessing the DB and hence stopping the main thread with a possible ANR problem?

If I were to write the code without LiveData (like in the old days), you would still have to make it async from the main thread (e.g. co-routine with I/O scheduler) because even read operations can take some time, in order to avoid ANR problems?

**Comment by Kraigolas** [comment]
Keep in mind that `LiveData<Plant>` is _not_ a `Plant` object. `LiveData` must be observed by calling its `observe` method. Because this observation is perpetual, you can safely assume that it is not done on the main thread.

**Comment by eothein** [comment]
Thanks for the explanation!

**Comment by CharlieTap** [comment]
In fact the above isnt quite right @eothein , realistically the DAO should expose suspend functions for insertions and Flows instead of LiveData for queries, with the repository doing the same and finally the viewmodel applying .toLiveData on the flows. The reason being that the combinators available on the coroutines flows are far superior to LiveData, Flow isn't miles away from Rx in regards to composability. 

As a note, in the future LiveData will likely be deprecated in favour of a pure coroutines solution in the form of the new StateFlow type in coroutines.

**Comment by eothein** [comment]
So how would this be implemented in the future? Small code example possible @CharlieTap ?

**Comment by CharlieTap** [comment]
For example:

`fun getPlant(plantId: String): Flow<Plant>` in the PlantDao
`fun getPlant(plantId: String) = plantDao.getPlant(plantId)` remains unchanged in terms of impl but returns a flow

I've not seen anyone actually use the Flow lib for the next step but in theory

`val plant = plantRepository.getPlant(plantId).shareIn(viewModelScope)`


Implementation in the view will then look something like:

Activity:
`lifecycleScope.launchWhenStarted {
        viewmodel.plant.collect {
            ...
        }
    }`

Fragment:

```
viewLifecycleOwner.lifecycleScope.launchWhenStarted {
        viewmodel.plant.collect {
            ...
        }
    }
```

**Comment by tiembo** [comment]
We added Flow in #671 - please take a look!

Closing this for now; feel free to reopen or add a new issue if you'd like to see more details about Flow implementation.
