### ISSUE TITLE
Introducing Flows in data layer (database)

### ISSUE THREAD

**Issue by mr3y-the-programmer** [android/sunflower#651]
I've noticed that things like [`PlantDao`](https://github.com/android/sunflower/blob/master/app/src/main/java/com/google/samples/apps/sunflower/data/PlantDao.kt) and [`GardenPlantingDao`](https://github.com/android/sunflower/blob/master/app/src/main/java/com/google/samples/apps/sunflower/data/GardenPlantingDao.kt) use LiveData to give an observation of their queries, Wouldn't it be much nicer to use Flows instead? 
 I think it is more convenient to do so here, but also it is a bit of architecture related change. So I opened this issue to discuss if this is something encouraged to be done or maybe project maintainers have another point of view about keeping the architecture as simple as possible particularly for beginners or those who aren't familiar with Flows.

**Comment by tiembo** [comment]
Thanks for filing this request.  We're looking into implementing this.

**Comment by tiembo** [comment]
Done in #671

**Comment by neiljaywarner** [comment]
@tiembo  I've been trying to learn about this; can you please comment here WHY this is nicer?  thanks
