### ISSUE TITLE
Should I always create corouine in viewmodel when not ui-only operation?

### ISSUE THREAD

**Issue by juneleaf** [android/sunflower#681]
It is said 'The ViewModel/Presenter layer should create coroutines' in
https://medium.com/androiddevelopers/coroutines-patterns-for-work-that-shouldnt-be-cancelled-e26c40f142ad
if i want to do some requeset only return success/failed such as register, submit. Is it also better to use viewModelScope, and observe a Livedata such as Result<Any> in Activity?
or use lifeCycleScope then i call this request without Callback in Activity?

**Comment by arriolac** [comment]
Please see the patterns in the app - a `viewModelScope` was used within ViewModels to initiate a suspending function and results were observed from the UI layer via Flows (previously was using LiveData)
