### ISSUE TITLE
Dao tests still use getValue for livedata when you have Flow returned from db

### ISSUE THREAD

**Issue by raghunandankavi2010** [android/sunflower#691]
Tests for Dao are using livedata (assertThat(getValue(gardenPlantingDao.getGardenPlantings()).size, equalTo(2))) https://github.com/android/sunflower/blob/main/app/src/androidTest/java/com/google/samples/apps/sunflower/data/GardenPlantingDaoTest.kt and in actual implementation https://github.com/android/sunflower/blob/main/app/src/main/java/com/google/samples/apps/sunflower/data/GardenPlantingDao.kt koltin flow is used.

**Comment by tiembo** [comment]
Fixed in #692
