### ISSUE TITLE
A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution

### ISSUE THREAD

**Issue by cikichen** [android/sunflower#713]
```
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols NO-SOURCE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:kaptDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by f2janyway** [comment]
same issue.

[this](https://gist.github.com/f2janyway/35f03c3cfe6287de4911cd2b189c57ad) is debug log when build.


android-studio info
---
Android Studio Bumblebee | 2021.1.1 Canary 1
Build #AI-203.7717.56.2111.7361063, built on May 14, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12
Registry: undo.documentUndoLimit=150, external.system.auto.import.disabled=true
Non-Bundled Plugins: IdeaVIM, com.thoughtworks.gauge, org.jetbrains.kotlin, org.intellij.plugins.markdown
---

**Comment by Calc86** [comment]
fix for macos

app/build.gradle 

add

```
import org.gradle.internal.os.OperatingSystem

dependencies {
    // Room DB
    if (OperatingSystem.current().isMacOsX()) {
        kapt "org.xerial:sqlite-jdbc:3.34.0"
    }
....
}

```

**Comment by calren** [comment]
Do you mind updating to the latest stable version of Android Studio (Arctic Fox) and seeing if the issue still exists? I'm able to reproduce the issue on my mac running Android Studio Arctic Fox

**Comment by f2janyway** [comment]
I solved this problem. After setting change. Thank you.

2021년 9월 25일 (토) 오전 7:05, Caren ***@***.***>님이 작성:

**Comment by sanketkumbhare** [comment]
I am using android studio bumblebee and having the same issue

Execution failed for task ':app:kaptDevKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

**Comment by arriolac** [comment]
Doing an issue scrub - the app has since been migrated from kapt to ksp. Please feel free to reopen if this is still an issue.
