### ISSUE TITLE
Stuck at the middle of ViewPager.

### ISSUE THREAD

**Issue by forceporquillo** [android/sunflower#715]
Every time I swipe back and forth, it keeps stuck in the middle of ViewPager. 

This glitch happens on Pixel API 30 emulator.

```
I/Choreographer: Skipped 139 frames!  The application may be doing too much work on its main thread.
```
![Screenshot_20210516_111905](https://user-images.githubusercontent.com/51302519/118384452-a3f37f80-b638-11eb-938e-7489774ed509.png)

**Comment by EliYakubov77** [comment]
Did you find a solution to this problem?
Please

**Comment by arriolac** [comment]
The app has since been migrated to Compose. Please reopen a new issue if you are still seeing this on the current version of the app
