### ISSUE TITLE
What's the point of class 'PlantAndGardenPlantings'?

### ISSUE THREAD

**Issue by duwangthefirst** [android/sunflower#718]
In my view, the relation between **Plant** and **GardenPlanting** should be **OneToOne**, while the **PlantAndGardenPlantings** class defines a **OneToMany** relation, which confuses me a lot.

**Comment by arriolac** [comment]
I see the confusion - while the UI only permits planting one plant in your garden, conceptually you can plant multiple of the same plant in your garden hence the one-to-many relationship.
