### ISSUE TITLE
Collapsing Toolbar broken on Pixel 4a 5G

### ISSUE THREAD

**Issue by caitlyn-alltrails** [android/sunflower#723]
In the screenshot you can see that part of the Sunflower title and the option menu icon are visible in the status bar when the toolbar is fully collapsed.

![Screenshot_20210621-171449](https://user-images.githubusercontent.com/79473007/122843506-768f9680-d2b4-11eb-8ce2-72c4adccf376.png)

**Comment by arriolac** [comment]
Tested this on a Pixel 4a emulator and verified that it's no longer an issue since the app was migrated to Material 3
