### ISSUE TITLE
Adding a preference screen to adjust the theme of app

### ISSUE THREAD

**Issue by arinarora18** [android/sunflower#738]
An option to switch to dark theme for user.

**Comment by prashantkr006** [comment]
may I work on this issue?

**Comment by calren** [comment]
I believe users can switch to dark theme in the Settings screen, so we don't currently have plans to add an extra preference screen for now.

**Comment by calren** [comment]
closing this out in favor of this similar issue https://github.com/android/sunflower/issues/316
