### ISSUE TITLE
Bug: Too many chances to open "drawer"

### ISSUE THREAD

**Issue by XinyueZ** [android/sunflower#79]
There're too many approaches to open "drawer".

1. Garden-list, with "burg" button
2. Plant-list, with "arrow" button
3. In detail screen

How about using a solution of bottom-bar which is also an approach of MD, right @andhie , @tiembo ?

**Comment by andhie** [comment]
The guideline says Bottom Navigation is suitable if you have 3 to 5 tabs.
As i can see, the app only has 2 top level screen. (unless you can figure out what the 3rd tab does)
In such case, using `ViewPager` with `TabLayout` is more suitable instead

https://material.io/design/components/bottom-navigation.html
https://material.io/design/components/navigation-drawer.html

**Comment by XinyueZ** [comment]
@andhie Also a good idea.

**Comment by andhie** [comment]
however, i would still prefer to do something that would make use of Navigation (to demo its capability). so i would lean towards BottomNavigation with 3 tabs. perhaps the 3rd tab can be About screen or similar?

**Comment by tiembo** [comment]
Thanks for the discussion @XinyueZ and @andhie.  Yes, the navigation should move from a Navigation Drawer to Bottom Navigation.  In addition to "My Garden" and "Plant List", the additional destination(s) can be a Settings destination and possible an About destination.

Agree right now that it's a bit confusing that the nav drawer is accessible via the plant detail page.

**Comment by tiembo** [comment]
Also, https://issuetracker.google.com/issues/80029773 address reconciling Navigation and Material guidelines.

**Comment by andhie** [comment]
> Agree right now that it's a bit confusing that the nav drawer is accessible via the plant detail page.
The guideline didnt specify in detail screen that the drawer is not accessible. if you take note, the Google Play Store can access the drawer via edge swipe even in app detail page.

**Comment by tiembo** [comment]
Closing outdated issue as the navigation drawer has since been removed.
