### ISSUE TITLE
The file not running in my android studio despite cloned/forked.

### ISSUE THREAD

**Issue by SwapnilSonker** [android/sunflower#821]
The file not running, despite being cloned and forked 
![Screenshot (28)](https://user-images.githubusercontent.com/90846252/210209264-67447500-0391-48a7-ba03-828bdd5b3053.png)

please help me, I am new to android development.

**Comment by arriolac** [comment]
Upon cloning this project, go to `File` -> `New` -> `Import Project`. A configuration should be available to run the `app` module at that point. Comment back here if you have further issues
