### ISSUE TITLE
[went wrong]Could not resolve all files for configuration ':app:debugAndroidTestRuntimeClasspath'

### ISSUE THREAD

**Issue by quibbler01** [android/sunflower#830]
The error is as follows：

* What went wrong:
Execution failed for task ':app:desugarDebugAndroidTestFileDependencies'.
> Could not resolve all files for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not find androidx.compose.ui:ui-test-junit4:.
     Required by:
         project :app

**Comment by arriolac** [comment]
This is fixed in 1ee99d5e
