### ISSUE TITLE
Info - Gallery button activation issue? (Maybe not.)

### ISSUE THREAD

**Issue by hhyeok1026** [android/sunflower#855]
Written for newbies to this repository like me.
On the detail screen, to the right of the plant name is a button that takes you to the gallery screen.

Even though I put the unsplash key in the main branch, the button to view the gallery is not activated,
**After deleting the gradle cache in the ide and rebuilding it, the gallery button was activated.**

However, before deleting the cache, I confirmed that there was a value in BuildConfig in the main branch (sorry, now that I think about it, I wonder if I checked that the gallery button was activated)

(Anyway, keep this **as a reference** to clear the Gradle cache and rebuild if you run into this problem).

In the view branch, it worked right away with the gradle cache without any problems.
→ It could be a simple ide problem.

**Comment by arriolac** [comment]
Thanks for sharing to help others. Since this isn't an active issue—closing this out.
