### ISSUE TITLE
App title moves. (ui problem)

### ISSUE THREAD

**Issue by hhyeok1026** [android/sunflower#857]
The title written "sunflower" in the app bar moves when the tab is changed.

In My garden, the title is central. 
 In the plant list, the title is moved to the left.

![image.jpg1](https://github.com/android/sunflower/assets/32453824/9abd3d8c-7b08-4a0c-8def-5453837bdd0f) |![image.jpg2](https://github.com/android/sunflower/assets/32453824/7df5df52-e03a-4ba4-82d6-963d62d20c76)
--- | --- |   

It may not be a bug, but
The ideal UI, in my opinion, is considered centrally fixed.

**Comment by essy16** [comment]
I think the reason of the changing fixed position is due to the CollapsingToolBar Layout that was implemented in the app ...I'd advise for you to research more on the Collapsing ToolBar Layout

**Comment by sahilsk3333** [comment]
We can use CenterAlignedTopAppBar instead of TopAppBar

**Comment by arriolac** [comment]
Closed by #930
