### ISSUE TITLE
add loader in image 

### ISSUE THREAD

**Issue by qamarelsafadi** [android/sunflower#867]
### What happened  

This is a suggestion to add a loader inside Async Image on Compose to let the user know that the image is loading to preview,
instead of showing white space, we can add a progress bar that describes the image loading to preview.

This is the current 👇🏻 : 

https://github.com/android/sunflower/assets/30949634/7146fa1b-e25f-4d07-8775-b4d370bb386e

What I suggest showing is  something like that 👇🏻 : 

https://github.com/android/sunflower/assets/30949634/9a1b4cb2-1fde-4280-889e-17a5c60b9ace

### 

Part of [GTC](https://www.facebook.com/groups/gazatechcommunity/) open source initiative

**Comment by arriolac** [comment]
Please add more details in the description

**Comment by arriolac** [comment]
Yep - since this is a fairly minor enhancement it can be added to the app. I'd say lower priority than other issues though
