### ISSUE TITLE
Why no option to remove plant from my garden?

### ISSUE THREAD

**Issue by abduldblogger** [android/sunflower#87]
Hi,
There should be an option to remove plant from my garden.

**Comment by abduldblogger** [comment]
I mean if I add a plant from list, then there should be an option to remove that plant from GardenActivity list

**Comment by williamwue** [comment]
@abduldblogger I have same idea with you

**Comment by XinyueZ** [comment]
@tiembo  How about "delete" on plants in the garden?

**Comment by williamwue** [comment]
@tiembo @XinyueZ I have interesting to implement it, could you let me have try?

**Comment by tiembo** [comment]
@williamwue sure, feel free to open a pull request. Thanks!

**Comment by williamwue** [comment]
@tiembo I have completed the feature in #91 , could you help merge it? Thx!

**Comment by williamwue** [comment]
@tiembo I have creat new PR #169 about this feature, the old one is closed.

**Comment by kyawthura18115** [comment]
Automobileengineeringservices@googlemail.com

**Comment by robsonsamurai** [comment]
Hello dear developers, sunflower application.
Already 2020, is it really difficult to add functionality to remove plants from the garden?
Please add this functionality as an example, this is 1 hour work.

**Comment by robsonsamurai** [comment]
Hello dear developers, sunflower application.
Already 2020, is it really difficult to add functionality to remove plants from the garden?
Please add this functionality as an example, this is 1 hour work.

**Comment by nic0lette** [comment]
Hi @robsonsamurai ! Please feel free to open a PR to address the issue, if you'd like to take on adding this feature.
