### ISSUE TITLE
change Gallery screen top bar background color to match the entire app 

### ISSUE THREAD

**Issue by qamarelsafadi** [android/sunflower#876]
### It looked purple  

<img width="331" alt="Screenshot 2023-06-22 at 7 12 32 PM" src="https://github.com/android/sunflower/assets/30949634/7503a5f1-71c3-420f-80e8-05451890f030">

### It needs to be green

<img width="331" alt="Screenshot 2023-06-22 at 7 11 45 PM" src="https://github.com/android/sunflower/assets/30949634/47ebacaf-9ffe-4b8e-8bf5-9201fe80edf9">

Part of [GTC](https://www.facebook.com/groups/gazatechcommunity/) open source initiative

**Comment by Ahmadazbieda** [comment]
<style name="AppTheme" parent="Theme.AppCompat.Light">
    <item name="colorPrimary">#FF0000</item> 
</style>

**Comment by Ahmadazbieda** [comment]
<item name="colorPrimary">#FF0000</item>

**Comment by arriolac** [comment]
What branch? I'm not seeing this on the `main` branch, this is what I see instead:
![Screenshot_20230626_132400](https://github.com/android/sunflower/assets/463186/501a2dc0-834e-4c85-842b-cdf9159d665e)

**Comment by qamarelsafadi** [comment]
yeah seems like I was on my own converting to m3 branch, Sorry for that
