### ISSUE TITLE
[Bug]: The filter icon duplicate

### ISSUE THREAD

**Issue by yosefmoq** [android/sunflower#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to the sample app?

- [X] Yes, this is a specific issue related to this samples repo.

### What happened?

**The filter icon duplicates whenever I go back from the plant details screen.**

https://github.com/android/sunflower/assets/30843492/b0e03564-021a-4181-adb7-54fc60f008ec

![image](https://github.com/android/sunflower/assets/30843492/02a2a0ba-c5b9-4416-b53f-e3ce6b2db385)

Part of [GTC](https://www.facebook.com/groups/gazatechcommunity/) open source initiative

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arriolac** [comment]
Closed by #883
