### ISSUE TITLE
Remove commented code

### ISSUE THREAD

**Issue by arononak** [android/sunflower#897]
https://github.com/android/sunflower/blob/d01598647ec65c028e9eb15df3a916359aeb9443/.github/workflows/android.yml#L45C2-L45C2

remove it guys because it is hands down.  I wonder what you will do when im gone

**Comment by ricele-dz** [comment]
good

**Comment by arriolac** [comment]
Commented-out code is still useful. The change is rather to uncomment it out and get it working (there is a linked internal bug in the comment)
