### ISSUE TITLE
[Bug]: Toolbar is not collapsing well on Dark Mode

### ISSUE THREAD

**Issue by qamarelsafadi** [android/sunflower#900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to the sample app?

- [X] Yes, this is a specific issue related to this samples repo.

## Dark Mode in the main branch

in GardenActivity when scrolls to collapse toolbar Dark mode have a strange behavior as its just becoming Transapernent and the toolbar is not really being collapsed. 

### Video to explain 👇🏻 

https://github.com/android/sunflower/assets/30949634/79389bdb-43dc-4099-a231-0d7b43c7df23

## 
#### Device I am using to test 

<img width="363" alt="Screenshot 2023-07-07 at 6 11 46 PM" src="https://github.com/android/sunflower/assets/30949634/88b6a6cb-a606-43e5-84d7-d606b982b5b7">

## 

Part of [GTC](https://www.facebook.com/groups/gazatechcommunity/) open source initiative

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayaankhan98** [comment]
This issue is already fixed in m3
https://github.com/android/sunflower/blob/dff09b3af8cfceb794462b11af220ef4830ec70f/app/src/main/java/com/google/samples/apps/sunflower/compose/home/HomeScreen.kt#L76

**Comment by arriolac** [comment]
Closed by #883
