### ISSUE TITLE
[Bug]: Plus icon not visible on plant details screen at m3 in Dark Mode

### ISSUE THREAD

**Issue by ayaankhan98** [android/sunflower#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to the sample app?

- [X] Yes, this is a specific issue related to this samples repo.

### What happened?

Plus on icon is not properly visible, see screenshot below.
![2023-08-02-024632_1920x1080_scrot](https://github.com/android/sunflower/assets/43348292/ed590ed8-8a84-4d6d-b418-f1ab729e98e8)

### Relevant logcat output

```shell
No log cat
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayaankhan98** [comment]
Solution would be to use `onTertiary` instead of `onSurface` in
https://github.com/android/sunflower/blob/dff09b3af8cfceb794462b11af220ef4830ec70f/app/src/main/java/com/google/samples/apps/sunflower/compose/plantdetail/PlantDetailView.kt#L362

and it will look like this 
![2023-08-02-025402_1920x1080_scrot](https://github.com/android/sunflower/assets/43348292/d2e59aec-0e4f-4410-b8be-cfffa6c34ead)

I will create a PR for this.

**Comment by arriolac** [comment]
Closed by #883
