### ISSUE TITLE
[Update]: Migrate [Hilt & Room] from KAPT to KSP

### ISSUE THREAD

**Issue by anselmoalexandre** [android/sunflower#917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Describe the problem

Keeping in mind that this is a Kotlin project, using KSP in favour of KAPT, makes much easier to understand Kotlin - specific features, makes much easier to develop lightweight compiler plugins and also it can run twice faster than KAPT annotation processor, etc.

### Describe the solution

Setup the migration from KAPT to KSP 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Code-indomitus** [comment]
Hi can I work on this?

**Comment by arriolac** [comment]
Please feel free to send us a PR :)
